version: '3.8'

services: # <-- Pastikan ini ada dan semua service menjorok ke dalam
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://fincaanaya:Basketismylife123@cluster0.1cad5ok.mongodb.net/toko_online?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=rahasia_super_kuat_123
    depends_on:
      - mongodb

  frontend: # <-- Sekarang ini berada di bawah 'services'
    build: ./frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes: # <-- Ini kembali ke baris paling depan (root)
  mongo-data: