version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-merchify
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - merchify-net

  backend:
    build: ./backend
    container_name: backend-merchify
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=
      - JWT_SECRET=
      - NODE_ENV=development
    depends_on:
      - mongodb
    networks:
      - merchify-net

  frontend:
    build: ./frontend
    container_name: frontend-merchify
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - merchify-net

networks:
  merchify-net:
    driver: bridge

volumes:
  mongo-data:
